/**
 * AutoFilm short-link worker — links.autofilm.io
 *
 * Contract (must stay in lockstep with backend/src/lib/cloudflare.js):
 *   KV key:   `v_${code}` (videos) or `t_${code}` (trade links)
 *   KV value: plain destination URL string (no JSON)
 *   Codes:    [A-Za-z0-9]{4,16}, generated by backend/src/lib/shortcode.js
 *
 * Bindings (wrangler.toml):
 *   LINKS      — KV namespace for code → destination URL
 *   ANALYTICS  — optional KV namespace for click counters
 */

const FALLBACK_URL = 'https://autofilm.io';
const ROUTE = /^\/(v|t)\/([A-Za-z0-9]{4,16})$/;

export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const match = url.pathname.match(ROUTE);

    if (!match) {
      // Health probe for uptime monitors
      if (url.pathname === '/health') {
        return new Response(JSON.stringify({ status: 'ok', service: 'autofilm-links' }), {
          headers: { 'Content-Type': 'application/json' },
        });
      }
      return Response.redirect(FALLBACK_URL, 302);
    }

    const [, type, code] = match;

    let dest = null;
    try {
      dest = await env.LINKS.get(`${type}_${code}`);
    } catch (err) {
      // KV read failure — fall through to fallback rather than erroring the customer
      console.log(`[links] KV read error for ${type}_${code}: ${err.message}`);
    }

    if (!dest) {
      return Response.redirect(FALLBACK_URL, 302);
    }

    // Best-effort click analytics — never block the redirect
    if (env.ANALYTICS) {
      ctx.waitUntil(recordClick(env.ANALYTICS, type, code, request));
    }

    return Response.redirect(dest, 302);
  },
};

async function recordClick(kv, type, code, request) {
  try {
    const day = new Date().toISOString().slice(0, 10);
    const key = `clicks_${type}_${code}_${day}`;
    const current = parseInt(await kv.get(key)) || 0;
    await kv.put(key, String(current + 1), { expirationTtl: 60 * 60 * 24 * 90 });

    // Device split for the dashboard
    const ua = request.headers.get('user-agent') || '';
    const device = /mobile|iphone|android/i.test(ua) ? 'mobile' : 'desktop';
    const dkey = `device_${type}_${code}_${device}`;
    const dcur = parseInt(await kv.get(dkey)) || 0;
    await kv.put(dkey, String(dcur + 1), { expirationTtl: 60 * 60 * 24 * 90 });
  } catch {
    // Analytics must never break redirects
  }
}
